config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
  end

  resources :users, only: [:index, :show] do 
    member do 
      get 'send_friend'
      patch 'update_friend'
      delete 'destroy_friend'
    end
  end

  resources :posts, only: [:index, :create] do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: %i[facebook]

  validates :name, presence: true, length: { maximum: 20 }

  has_many :posts
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :friendships, foreign_key: 'user_id'
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id'


  has_many :confirmed_friendships, -> { where(confirmed: true) }, class_name: 'Friendship'
  has_many :pending_friendships, -> { where(confirmed: false) }, class_name: 'Friendship', foreign_key: 'user_id'
  has_many :incoming_friendships, -> { where(confirmed: false) }, class_name: 'Friendship', foreign_key: 'friend_id'

  has_many :friends, through: :confirmed_friendships

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])
  
      if @user.persisted?
        sign_in_and_redirect @user #this will throw if @user is not activated
        set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
  
    def failure
      redirect_to root_path
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.ordered_by_most_recent
  end

  def send_friend
    Friendship.create(user_id: current_user.id, friend_id: params[:id], confirmed: false)

    redirect_to users_path, notice: 'Friend request sent.'
  end

  def update_friend
    @friendship = Friendship.find(params[:id])
    @friendship.update(confirmed: true)
    @friednship2 = Friendship.create(user_id: current_user.id, friend_id: @friendship.user_id, confirmed: true)
    redirect_back(fallback_location: root_path)
  end

  def destroy_friend
    @friendship = Friendship.find(params[:id])

    # rubocop:disable Layout/LineLength
    @friendship2 = Friendship.where(user_id: @friendship.friend_id, friend_id: @friendship.user_id, confirmed: true).first
    # rubocop:enable Layout/LineLength

    @friendship.destroy
    @friendship2.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 80 })
        size = options[:size]
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar, rounded-circle")
    end
end

app/views/users/index.html.erb
<section class="users-section">
  <ul class="users-list">
    <% @users.each do |user| %>
      <li>
        <%= gravatar_for user, size: 20 %>
        Name: <%= user.name %>
        <span class="profile-link">
          <%= link_to 'See Profile',  user_path(user), class: 'profile-link' %> | 
        </span>
        <% if current_user != user && friends_check(user) == false && pending_request(user) == false %>
          <%= link_to 'Send friend request', "/users/#{user.id}/send_friend", class: 'profile-link' %>
        <% elsif pending_request(user) %>
          <span class= 'profile-link'>Friend request pending</span> 
          <% if !@pending_request.blank? %>
            <span class= 'profile-link'><%= accept_friend(@pending_request) %> | <%= reject_friend(@pending_request) %></span>
          <% end %>
        <% elsif friends_check(user) %>
          <span class= 'profile-link'>Friends!!!</span> <span class= 'profile-link'><%= unfriend(user) %></span>
        <% end %>
      </li>
    <% end %>
  </ul>
</section>

app/views/users/show.html.erb
<section class="user-section">
  <h2><%= gravatar_for @user, size: 45 %><%= "Name: #{@user.name}" %></h2>  
  <% if current_user != @user && friends_check(@user) == false && pending_request(@user) == false %>
    <%= link_to 'Send friend request', send_friend_user_path, class: 'profile-link' %>
  <% elsif pending_request(@user) %>
    <span class= 'profile-link'>Friend request pending</span> 
          <% if !@pending_request.blank? %>
            <span class= 'profile-link'><%= accept_friend(@pending_request) %> | <%= reject_friend(@pending_request) %></span>
          <% end %>
  <% elsif friends_check(@user) %>
    <span class= 'profile-link'>Friends!!!</span> <%= unfriend(@user) %>
  <% end %>
  <% if current_user == @user %>
    <% if @user.incoming_friendships.any? %>
      <h4>Pending friendship requests: <%= @user.incoming_friendships.count %></h4>
      <ul>
        <% @user.incoming_friendships.each do |request| %>
          <li><%= gravatar_for request.user, size: 20 %><%= request.user.name %> | <%= accept_friend(request) %> | <%= reject_friend(request) %></li>
        <% end %>
      </ul>
    <% end %>
    <% if @user.friends.any? %>
      <h4>Friends: <%= @user.friends.count %></h4>
      <ul>
        <% @user.friends.each do |friend| %>
          <li><%= gravatar_for friend, size: 20 %><%= link_to friend.name, user_path(friend.id), class: 'profile-link' %> | <%= unfriend(friend) %>
        <% end %>
      </ul>
    <% end %>
  <% end %>


  <% if current_user == @user || friends_check(@user) %>
  <article class="timeline">
    <h3>Recent posts:</h3>
    <ul class="posts">
      <%= render @posts %>
    </ul>
  </article>
  <% end %>
</section>