config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
  end

  resources :users, only: [:index, :show] do 
    member do 
      get 'send_friend'
      patch 'update_friend'
      delete 'destroy_friend'
    end
  end

  resources :posts, only: [:index, :create] do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true, length: { maximum: 1000,
                                                too_long: '1000 characters in post is the maximum allowed.' }

  belongs_to :user

  scope :ordered_by_most_recent, -> { order(created_at: :desc) }
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user!

  def index
    @post = Post.new
    timeline_posts
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to posts_path, notice: 'Post was successfully created.'
    else
      timeline_posts
      render :index, alert: 'Post was not created.'
    end
  end

  private

  def friends_posts(user)
    user if friends_check(User.find(user)) || current_user.id == user
  end

  def timeline_posts
    @timeline_posts = Post.all.ordered_by_most_recent.includes(:user).select do |post|
      post.user_id == friends_posts(post.user_id)
    end
  end

  def post_params
    params.require(:post).permit(:content)
  end
end

app/views/posts/_post.html.erb
<li class="post">
  <div>
    <div class='post-attribution' >
      <%= gravatar_for post.user, size: 20 %>
      <%= link_to post.user.name, user_path(post.user), class: 'post-author' %>
    </div>
    <div class='post-liking'>
      <span class='post-date'> <%= post.created_at.strftime("%Y/%m/%d") %> </span>
      <%= like_or_dislike_btn(post) %> <%= post.likes.count %>
    </div>
  </div>
  <p class="post-content">
    <%= post.content %>
  </p>

  <div class='post-comments-section'>
  <p>Comments: <%= post.comments.count %></p>
    <% post.comments.each do |comment| %>
      <div class="post-comments">
        <p>
          <b><%= gravatar_for comment.user, size: 15 %> <%= comment.user.name %>:</b> <%= comment.content %>
        </p>
        <span> <%= comment.created_at.strftime("%Y/%m/%d") %> </span>
      </div>
    <% end %>

    <%= form_for(post.comments.new, url: post_comments_path(post)) do |form| %>
      <%= form.text_field :content, id: :comment_content, class: 'form-control', placeholder: 'Add new Comment' %>
      <%= form.submit 'Comment', class: 'btn btn-secondary' %>
    <% end %>
  </div>
</li>

app/views/posts/index.html.erb
<%= form_for(@post) do |form| %>
  <%= form.label :content %>
  <%= form.text_field :content, id: :post_content, class: 'form-control', placeholder: 'Add New Post' %>
  <% if @post.errors.full_messages.any? %>
    <p class="errors">
      <%= "Post could not be saved. #{@post.errors.full_messages.join('. ')}" %>
    </p>
  <% end %>
  <%= form.submit 'Save', class: 'btn btn-primary' %>
<% end %>

<article class="timeline">
  <h3>
    Recent posts
  </h3>
  <ul class="posts">
    <%= render @timeline_posts %>
  </ul>
</article>